#!/bin/bash

set -o errexit
set -o nounset

worker_ready() {
   uv run celery -A app.tasks inspect ping
}

until worker_ready; do
  >&2 echo 'Celery workers not available'
  sleep 1
done
>&2 echo 'Celery workers is available'

uv run celery flower \
    --app=app.tasks \
    --broker="${CELERY_BROKER_URL}"
