import type { Metadata } from "next"
import "@/app/globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <main className="flex justify-center items-center min-h-screen w-full px-10">
      {children}
    </main>
  )
}
