"""add custom fields and url to utm

Revision ID: be7c6fc00b28
Revises: 35d7fb99cf58
Create Date: 2026-06-01 20:54:23.709228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'be7c6fc00b28'
down_revision: Union[str, Sequence[str], None] = '35d7fb99cf58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utms', sa.Column('custom_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('utms', sa.Column('url', sa.String(length=100), nullable=False))
    op.drop_column('utms', 'details')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('utms', sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('utms', 'url')
    op.drop_column('utms', 'custom_fields')
    # ### end Alembic commands ###
