networks:
  social-network:
    driver: bridge

services:
  load-balancer:
    image: nginx
    container_name: social-network-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    networks:
      - social-network
    volumes:
      - ./.docker/nginx:/etc/nginx/conf.d
  app-1:
    container_name: social-app-instance-1
    build:
      dockerfile: ./.docker/app/Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - social-network
  app-2:
    container_name: social-app-instance-2
    build:
      dockerfile: ./.docker/app/Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - social-network
  app-3:
    container_name: social-app-instance-3
    build:
      dockerfile: ./.docker/app/Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - social-network
  db:
    container_name: social-media-db
    image: postgres:15
    restart: unless-stopped
    networks:
      - social-network
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "6543:5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGDATA: /var/lib/postgresql/15

volumes:
  postgres_data:
    driver: local
