networks:
  url-shortener:
    driver: bridge

services:
  celery-worker:
    build:
      context: .
      dockerfile: ./.docker/app/Dockerfile
    command: /start-celery-worker
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URI}
    restart: unless-stopped
    networks:
      - url-shortener
    volumes:
      - .:/app
    depends_on:
      - redis
      - db

  flower:
    build:
      context: .
      dockerfile: ./.docker/app/Dockerfile
    command: /start-flower
    environment:
      CELERY_BROKER_URL: ${CELERY_BROKER_URI}
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - "5557:5555"
    networks:
      - url-shortener
    depends_on:
      - redis
      - db

  redis:
    image: redis:7
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - url-shortener

  app:
    container_name: url-shortener-app
    build:
      context: .
      dockerfile: ./.docker/app/Dockerfile
    command: /start
    ports:
      - "127.0.0.1:8000:8000"
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - url-shortener

  db:
    container_name: url-shortener-db
    image: postgres:15
    restart: unless-stopped
    networks:
      - url-shortener
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "127.0.0.1:6543:5432"
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGDATA: /var/lib/postgresql/15

volumes:
  postgres_data:
    driver: local
